.TH velvet-keymap 3 "2026-04-03" "velvet" "Velvet Lua API"

.SH NAME
velvet.keymap \- managing key bindings

.SH DESCRIPTION
[Overview of keybind semantics. Compare and contrast to tmux / neovim]

.SS Key sequences
How they're formatted, what modifiers mean, etc.

.SS Binding scope
Where bindings live, how they interact with windows.

.SS Common workflows
[Real examples of typical usage patterns]

.SH EXAMPLES
[Realistic use cases, not toy examples]

.SH SEE ALSO
.BR velvet (1)
