.TH velvet-session-storage 3 "2026-04-03" "velvet" "Velvet Lua API"

.SH NAME
velvet.session_storage \- preserving state between reloads.

.SH DESCRIPTION

.SS The API

.SS Lifetime

.SS Common workflows

.SH EXAMPLES

.SH SEE ALSO
.BR velvet (1)
.BR velvet-keymap (3)
.BR velvet-session-storage (3)
