--[[
DO NOT EDIT THIS BY HAND
This file was auto generated by api_gen.lua
--]]

error("Cannot require meta file")

--- @meta
--- @class velvet.api
local api = {}

--- @enum velvet.api.transparency_mode
api.transparency_mode = {
  none = 1,
  clear = 2,
  all = 3,
}

--- @enum velvet.api.key_event_type
api.key_event_type = {
  press = 1,
  ['repeat'] = 2,
  release = 3,
}

--- @enum velvet.api.key_modifiers
api.key_modifiers = {
  shift = 1,
  alt = 2,
  ctrl = 4,
  super = 8,
  hyper = 16,
  meta = 32,
  caps_lock = 64,
  num_lock = 128,
}

--- @class velvet.api.rgb_color
--- @field red integer nil
--- @field green integer nil
--- @field blue integer nil

--- @class velvet.api.color_palette
--- @field black velvet.api.rgb_color|string Palette color 0
--- @field red velvet.api.rgb_color|string Palette color 1
--- @field green velvet.api.rgb_color|string Palette color 2
--- @field yellow velvet.api.rgb_color|string Palette color 3
--- @field blue velvet.api.rgb_color|string Palette color 4
--- @field magenta velvet.api.rgb_color|string Palette color 5
--- @field cyan velvet.api.rgb_color|string Palette color 6
--- @field white velvet.api.rgb_color|string Palette color 7
--- @field bright_black velvet.api.rgb_color|string Palette color 8
--- @field bright_red velvet.api.rgb_color|string Palette color 9
--- @field bright_green velvet.api.rgb_color|string Palette color 10
--- @field bright_yellow velvet.api.rgb_color|string Palette color 11
--- @field bright_blue velvet.api.rgb_color|string Palette color 12
--- @field bright_magenta velvet.api.rgb_color|string Palette color 13
--- @field bright_cyan velvet.api.rgb_color|string Palette color 14
--- @field bright_white velvet.api.rgb_color|string Palette color 15

--- @class velvet.api.window.geometry
--- @field left integer The leftmost cell of the window.
--- @field top integer The topmost cell of the window.
--- @field width integer The width of the window
--- @field height integer The height of the window

--- @class velvet.api.screen.geometry
--- @field width integer The width of the screen
--- @field height integer The height of the screen

--- @class velvet.api.window.created.event_args
--- @field id integer The id of the newly created window.

--- @class velvet.api.window.closed.event_args
--- @field id integer The id of the closed window.

--- @class velvet.api.window.moved.event_args
--- @field id integer The id of the resized window.
--- @field old_size velvet.api.window.geometry The old geometry of |id|.
--- @field new_size velvet.api.window.geometry The new geometry of |id|.

--- @class velvet.api.window.resized.event_args
--- @field id integer The id of the resized window.
--- @field old_size velvet.api.window.geometry The old geometry of |id|.
--- @field new_size velvet.api.window.geometry The new geometry of |id|.

--- @class velvet.api.window.focus_changed.event_args
--- @field old_focus integer The previous focused window.
--- @field new_focus integer The new focused window.

--- @class velvet.api.screen.resized.event_args
--- @field old_size velvet.api.screen.geometry The old screen size
--- @field new_size velvet.api.screen.geometry The new screen size

--- @class velvet.api.window.key_event
--- @field codepoint integer Unicode codepoint of the key generating the event.
--- @field alternate_codepoint integer Shifted unicode codepoint of the key generating the event. This is only set if the key was shifted.
--- @field name string Key name, such as 'F1'
--- @field event_type velvet.api.key_event_type Event type, such as key press, repeat, and release.
--- @field modifiers velvet.api.key_modifiers Key modifiers such as super, shift, ctrl, alt

--- @class velvet.api.window.on_key.event_args
--- @field win_id integer The id of the window the keys were sent to.
--- @field key velvet.api.window.key_event The key which generated the event.

--- Remap the modifier |from| to the modifier |to|. This is a one-way mapping. To swap two modifiers, you must also apply the inverse mapping. Shift is not supported.
--- @param from velvet.api.key_modifiers The modifier to remap.
--- @param to velvet.api.key_modifiers The new modifier emitted when the remapped modifier is used.
--- @return nil 
function api.keymap_remap_modifier(from, to) end

--- Delete the mapping associated with |keys|
--- @param keys string The mapping to remove
--- @return nil 
function api.keymap_del(keys) end

--- @class velvet.api.keymap_set.Opts
--- @field repeatable? boolean If set, this mapping may be repeated within the interval defined by |velvet.options.key_repeat_timeout|

--- Creates a mapping of |keys| to |function|
--- @param keys string Left hand side of the mapping
--- @param func fun(): nil Right hand side of the mapping
--- @param opts? velvet.api.keymap_set.Opts
--- @return nil 
function api.keymap_set(keys, func, opts) end

--- Get the size of the screen.
--- @return velvet.api.screen.geometry The geometry of the screen window.
function api.get_screen_geometry() end

--- Schedule |function| to run after at least |delay| ms
--- @param delay integer delay in miliseconds
--- @param func fun(): nil function to run
--- @return nil 
function api.schedule_after(delay, func) end

--- Get the number of milliseconds elapsed since startup
--- @return integer milliseconds elapsed since startup
function api.get_current_tick() end

--- Get the IDs of all sessions.
--- @return integer[] List of session IDs
function api.get_sessions() end

--- Get the id of the active session
--- @param session_id integer Session id
--- @return nil 
function api.set_active_session(session_id) end

--- Get the id of the active session
--- @return integer Session id
function api.get_active_session() end

--- Detach |session| session from the server.
--- @param session_id integer Session id
--- @return nil 
function api.session_detach(session_id) end

--- Kill the velvet instance. All child processes will be killed.
--- @return nil 
function api.server_kill() end

--- Get the IDs of all windows.
--- @return integer[] List of window IDs
function api.get_windows() end

--- Swap two windows. This affects the layout of tiled windows.
--- @param first integer Window id
--- @param second integer Window id
--- @return nil 
function api.swap_windows(first, second) end

--- Set the z index of |win| to |z|
--- @param win integer Window id
--- @param z integer New z index of |win|
--- @return nil 
function api.window_set_z_index(win, z) end

--- Get the z index of |win|
--- @param win integer Window id
--- @return integer The z index of |win|
function api.window_get_z_index(win) end

--- Set window hidden flag. A hidden window will not be rendered.
--- @param win_id integer Window id
--- @param hidden boolean New hidden state of |win_id|
--- @return nil 
function api.window_set_hidden(win_id, hidden) end

--- Get window hidden flag. A hidden window will not be rendered.
--- @param win_id integer Window id
--- @return boolean Bool indicating if the window is hidden.
function api.window_get_hidden(win_id) end

--- Get window opacity
--- @param win integer Window id
--- @return number The new window opacity.
function api.window_get_opacity(win) end

--- Set window opacity. The effect of this depends on the value of |window_get_transparency_mode|
--- @param win integer Window id
--- @param opacity number The new window opacity.
--- @return nil 
function api.window_set_opacity(win, opacity) end

--- Get window transparency mode.
--- @param win integer Window id
--- @return velvet.api.transparency_mode Set transparency mode.
function api.window_get_transparency_mode(win) end

--- Set window transparency mode.
--- @param win integer Window id
--- @param mode velvet.api.transparency_mode Set transparency mode.
--- @return nil 
function api.window_set_transparency_mode(win, mode) end

--- Get the current dim factor for |win|
--- @param win integer Window id
--- @return number Dim factor between 0.0 and 1.0
function api.window_get_dim_factor(win) end

--- Dim the window content of |win| by a constant factor. A larger value means more dimming (0.0 - 1.0)
--- @param win integer Window id
--- @param factor number Dim factor between 0.0 and 1.0
--- @return nil 
function api.window_set_dim_factor(win, factor) end

--- Get the id of the currently focused window.
--- @return integer TThe id of the currently focused window.
function api.get_focused_window() end

--- Focus the window with id |win_id|
--- @param win_id integer Window id
--- @return nil 
function api.set_focused_window(win_id) end

--- Get the geometry of the specified window.
--- @param win_id integer Window id
--- @return velvet.api.window.geometry 
function api.window_get_geometry(win_id) end

--- Set the geometry of the specified window.
--- @param win_id integer Window id
--- @param geometry velvet.api.window.geometry Window geometry
--- @return nil 
function api.window_set_geometry(win_id, geometry) end

--- Close the specified window, killing the associated process.
--- @param win_id integer The window to close
--- @return nil 
function api.window_close(win_id) end

--- Get the title of the window with id |win_id|
--- @param win_id integer Window id
--- @return string Window title
function api.window_get_title(win_id) end

--- Set the title of the window with id |win_id|
--- @param win_id integer Window id
--- @param title string New title
--- @return nil 
function api.window_set_title(win_id, title) end

--- Send |keys| to the window with id |win_id|. Unlike |window_send_text|, keys such as <C-x> will be encoded .
--- @param win_id integer The window receiving the keys
--- @param keys string The keys to send
--- @return nil 
function api.window_send_keys(win_id, keys) end

--- Send |text| to the window with id |win_id|
--- @param win_id integer The window receiving the text
--- @param text string The text to send
--- @return nil 
function api.window_send_text(win_id, text) end

--- Create a naked window with no backing process. This window can be controlled through the lua API. Returns the window id.
--- @return integer The id of the new window
function api.window_create() end

--- Write to the backing emulator of a window. This is only valid for naked windows, and will error if the |win_id| is process backed. The backing emulator acts like screen pty, and will parse ansi escapes such as \r, \n, color escapes, cursor movement, etc.
--- @param win_id integer Window id
--- @param text string String which can embed any VT compatible ansi escape.
--- @return nil 
function api.window_write(win_id, text) end

--- Create a new window with the process |cmd|, executed with 'sh -c'. Returns the window id.
--- @param cmd string The process to spawn.
--- @return integer The id of the new window
function api.window_create_process(cmd) end

--- Returns true if |win_id| exists and is a lua window.
--- @param win_id integer Window id
--- @return boolean Bool indicating if |win_id| is naked.
function api.window_is_lua(win_id) end

--- Returns true if a window exists with id |win_id|.
--- @param win_id integer Window id
--- @return boolean Bool indicating whether the window id is valid.
function api.window_is_valid(win_id) end

--- Get focus_follows_mouse
--- @return boolean The current value
function api.get_focus_follows_mouse() end

--- Set focus_follows_mouse. Returns the new value.
--- @param new_value boolean Automatically focus a window when the mouse moves over it.
--- @return boolean The value after the update
function api.set_focus_follows_mouse(new_value) end

--- Get key_repeat_timeout
--- @return integer The current value
function api.get_key_repeat_timeout() end

--- Set key_repeat_timeout. Returns the new value.
--- @param new_value integer Time in milliseconds before pending keybinds time out
--- @return integer The value after the update
function api.set_key_repeat_timeout(new_value) end

--- Get display_damage
--- @return boolean The current value
function api.get_display_damage() end

--- Set display_damage. Returns the new value.
--- @param new_value boolean Enable damage tracking when the screen is updated. (debugging feature)
--- @return boolean The value after the update
function api.set_display_damage(new_value) end

--- Get color_palette
--- @return velvet.api.color_palette The current value
function api.get_color_palette() end

--- Set color_palette. Returns the new value.
--- @param new_value velvet.api.color_palette The 16 numbered terminal colors.
--- @return velvet.api.color_palette The value after the update
function api.set_color_palette(new_value) end

--- @class velvet.api.event_handler
--- @field name string The name of the handler
--- @field id integer The id of the handler
--- @field window_created? fun(event_args: velvet.api.window.created.event_args): nil Raised after a new window is created.
--- @field window_closed? fun(event_args: velvet.api.window.closed.event_args): nil Raised after a window is closed.
--- @field window_moved? fun(event_args: velvet.api.window.moved.event_args): nil Raised after a window is moved.
--- @field window_resized? fun(event_args: velvet.api.window.resized.event_args): nil Raised after a window is resized.
--- @field window_on_key? fun(event_args: velvet.api.window.on_key.event_args): nil Raised when a key is sent to a lua window.
--- @field window_focus_changed? fun(event_args: velvet.api.window.focus_changed.event_args): nil Raised after focus changes.
--- @field screen_resized? fun(event_args: velvet.api.screen.resized.event_args): nil Raised after the screen is resized.

