--[[
DO NOT EDIT THIS BY HAND
This file was auto generated by api_gen.lua
--]]

--- The async API is a coroutine based implementation of velvet's event system, enabling linear control flow.
local M = {}

local e = require('velvet.events').create_group('velvet.async', true)
local registered_waits = {}
local sequence_callbacks = {}
local co_to_seq = {}
-- Monotonically increasing sequence number used to invalidate multi-waits
local sequence = 1

--- Execute |f| as a coroutine.
--- @param f fun(...): any
--- @param ... any arguments passed to f
--- @return thread co the coroutine executing |f|. Can be cancelled with M.cancel()
function M.run(f, ...)
  local args = table.pack(...)
  local co = coroutine.create(function()
    local ok, err = xpcall(f, debug.traceback, table.unpack(args, 1, args.n))
    if not ok then
      vv.log(("Unhandled error in coroutine: %s"):format(err), 'error')
    end
  end)
  coroutine.resume(co)
  return co
end

--- Cancel all continuations for |co|
--- @param co thread the thread to cancel
function M.cancel(co)
  local seq = co_to_seq[co]
  if seq then
    co_to_seq[co] = nil
    sequence_callbacks[seq] = nil
  end
end

local function resolve(name, ...)
  local current_sequence = sequence
  local function resolve_table(tbl, ...)
    -- capture the current sequence number and ensure we don't resolve anything higher.
    -- Otherwise a waiter() invocation can trigger on the currently processing event.
    for seq, _ in pairs(tbl) do
      if seq <= current_sequence then
        local waiter = sequence_callbacks[seq]
        if waiter then
          sequence_callbacks[seq] = nil
          waiter(name, ...)
        end
        tbl[seq] = nil
      end
    end
  end
  local named = registered_waits[name] or {}
  resolve_table(named, ...)
  local any = registered_waits.any or {}
  resolve_table(any, ...)
end

e.any = resolve

--- @alias velvet.async.event
---| 'session_on_key' Raised when a key is pressed.
---| 'window_created' Raised after a new window is created.
---| 'window_closed' Raised after a window is closed.
---| 'window_output' Raised when a window produces output.
---| 'window_moved' Raised after a window is moved.
---| 'window_resized' Raised after a window is resized.
---| 'window_on_key' Raised when a key is sent to a lua window.
---| 'window_focus_changed' Raised after focus changes.
---| 'screen_resized' Raised after the screen is resized.
---| 'mouse_move' Raised when the mouse moves.
---| 'mouse_click' Raised when the mouse is clicked.
---| 'mouse_scroll' Raised when the mouse scrolls.
---| 'system_message' Raised when the system logs an error message
---| 'pre_render' Raised right before content is rendered. This is useful for applying updates just-in-time.
---| 'pre_reload' Raised before reloading. This event can be used to store state.
---| 'any' Raised when any event is raised.

--- Wait for one of the events to fire, or |timeout|.
--- @param ... velvet.async.event|integer One or more events to wait for. A number can optionally be parsed which will be interpreted as the timeout in milliseconds.
--- @return velvet.async.event|'timeout', table The name of the event and the result, or nil on 'timeout'
function M.wait(...)
  local timeout = nil
  local co = coroutine.running()
  sequence = sequence + 1
  -- local capture to preserve the sequence number
  local seq = sequence

  local args = {...}
  if #args == 0 then error("No events specified.") end
  for i, evt in ipairs(args) do
    if type(evt) ~= 'number' and type(evt) ~= 'string' then
      error(("Bad argument #%d (number or string expected)"):format(i))
    end
  end

  co_to_seq[co] = seq
  sequence_callbacks[seq] = function(evt, ...)
    if timeout then vv.api.schedule_cancel(timeout) end
    local ok, error = coroutine.resume(co, evt, ...)
    if not ok then
      vv.log(("Unhandled error in coroutine: %s (event: %s)"):format(error, evt), 'error')
      vv.log(debug.traceback(error, 0), 'debug')
    end
  end

  for _, evt in ipairs(args) do
    if type(evt) == 'number' then
      timeout = vv.api.schedule_after(evt, function()
        -- if sequence_callbacks was unset, that means this coroutine was cancelled.
        if not sequence_callbacks[seq] then return end
        sequence_callbacks[seq] = nil
        local ok, error = coroutine.resume(co, "timeout")
        if not ok then
          vv.log(("Unhandled error in coroutine: %s (event: timeout)"):format(error), 'error')
          vv.log(debug.traceback(error, 0), 'debug')
        end
      end)
    else
      local tbl = registered_waits[evt]
      if not tbl then tbl = {} ; registered_waits[evt] = tbl end
      tbl[seq] = true
    end
  end

  return coroutine.yield()
end

--- Wait for session_on_key
--- @param timeout? integer Optional timeout.
--- @return velvet.api.session.key.event_args ret Result, or nil on timeout.
function M.wait_for_session_on_key(timeout)
  return select(2, M.wait('session_on_key', timeout))
end

--- Wait for window_created
--- @param timeout? integer Optional timeout.
--- @return velvet.api.window.created.event_args ret Result, or nil on timeout.
function M.wait_for_window_created(timeout)
  return select(2, M.wait('window_created', timeout))
end

--- Wait for window_closed
--- @param timeout? integer Optional timeout.
--- @return velvet.api.window.closed.event_args ret Result, or nil on timeout.
function M.wait_for_window_closed(timeout)
  return select(2, M.wait('window_closed', timeout))
end

--- Wait for window_output
--- @param timeout? integer Optional timeout.
--- @return velvet.api.window.output.event_args ret Result, or nil on timeout.
function M.wait_for_window_output(timeout)
  return select(2, M.wait('window_output', timeout))
end

--- Wait for window_moved
--- @param timeout? integer Optional timeout.
--- @return velvet.api.window.moved.event_args ret Result, or nil on timeout.
function M.wait_for_window_moved(timeout)
  return select(2, M.wait('window_moved', timeout))
end

--- Wait for window_resized
--- @param timeout? integer Optional timeout.
--- @return velvet.api.window.resized.event_args ret Result, or nil on timeout.
function M.wait_for_window_resized(timeout)
  return select(2, M.wait('window_resized', timeout))
end

--- Wait for window_on_key
--- @param timeout? integer Optional timeout.
--- @return velvet.api.window.on_key.event_args ret Result, or nil on timeout.
function M.wait_for_window_on_key(timeout)
  return select(2, M.wait('window_on_key', timeout))
end

--- Wait for window_focus_changed
--- @param timeout? integer Optional timeout.
--- @return velvet.api.window.focus_changed.event_args ret Result, or nil on timeout.
function M.wait_for_window_focus_changed(timeout)
  return select(2, M.wait('window_focus_changed', timeout))
end

--- Wait for screen_resized
--- @param timeout? integer Optional timeout.
--- @return velvet.api.screen.resized.event_args ret Result, or nil on timeout.
function M.wait_for_screen_resized(timeout)
  return select(2, M.wait('screen_resized', timeout))
end

--- Wait for mouse_move
--- @param timeout? integer Optional timeout.
--- @return velvet.api.mouse.move.event_args ret Result, or nil on timeout.
function M.wait_for_mouse_move(timeout)
  return select(2, M.wait('mouse_move', timeout))
end

--- Wait for mouse_click
--- @param timeout? integer Optional timeout.
--- @return velvet.api.mouse.click.event_args ret Result, or nil on timeout.
function M.wait_for_mouse_click(timeout)
  return select(2, M.wait('mouse_click', timeout))
end

--- Wait for mouse_scroll
--- @param timeout? integer Optional timeout.
--- @return velvet.api.mouse.scroll.event_args ret Result, or nil on timeout.
function M.wait_for_mouse_scroll(timeout)
  return select(2, M.wait('mouse_scroll', timeout))
end

--- Wait for system_message
--- @param timeout? integer Optional timeout.
--- @return velvet.api.system_message.event_args ret Result, or nil on timeout.
function M.wait_for_system_message(timeout)
  return select(2, M.wait('system_message', timeout))
end

--- Wait for pre_render
--- @param timeout? integer Optional timeout.
--- @return velvet.api.pre_render.event_args ret Result, or nil on timeout.
function M.wait_for_pre_render(timeout)
  return select(2, M.wait('pre_render', timeout))
end

--- Wait for pre_reload
--- @param timeout? integer Optional timeout.
--- @return velvet.api.pre_reload.event_args ret Result, or nil on timeout.
function M.wait_for_pre_reload(timeout)
  return select(2, M.wait('pre_reload', timeout))
end
return M
