--- DO NOT EDIT THIS BY HAND
--- This file was auto generated by api_gen.lua
--- It sets all options to their default values.

vv.options.focus_follows_mouse = true
vv.options.key_repeat_timeout = 500
vv.options.display_damage = false
vv.options.theme = {
  background = "#1e1e2e",
  black = "#45475a",
  blue = "#89b4fa",
  bright_black = "#585b70",
  bright_blue = "#89b4fa",
  bright_cyan = "#94e2d5",
  bright_green = "#a6e3a1",
  bright_magenta = "#f5c2e7",
  bright_red = "#f38ba8",
  bright_white = "#a6adc8",
  bright_yellow = "#f9e2af",
  cursor_background = "#f5e0dc",
  cursor_foreground = "#1e1e2e",
  cyan = "#94e2d5",
  foreground = "#cdd6f4",
  green = "#a6e3a1",
  magenta = "#f5c2e7",
  red = "#f38ba8",
  white = "#bac2de",
  yellow = "#f9e2af"
}

--- Populate all enum tables. These enums are used for interfacing with API functions

vv.api.transparency_mode = {
  none = 1,
  clear = 2,
  all = 3,
}

vv.api.key_event_type = {
  press = 1,
  ['repeat'] = 2,
  release = 3,
}

vv.api.key_modifiers = {
  shift = 1,
  alt = 2,
  ctrl = 4,
  super = 8,
  hyper = 16,
  meta = 32,
  caps_lock = 64,
  num_lock = 128,
}

vv.api.scroll_direction = {
  up = 0,
  down = 1,
  left = 2,
  right = 3,
}

vv.api.mouse_button = {
  left = 0,
  middle = 1,
  right = 2,
  none = 3,
}

vv.api.mouse_event_type = {
  mouse_down = 1,
  mouse_up = 2,
}

