--- DO NOT EDIT THIS BY HAND
--- This file was auto generated by api_gen.lua
--- It sets all options to their default values.

vv.options.focus_follows_mouse = true
vv.options.key_repeat_timeout = 500
vv.options.display_damage = false

--- Populate all enum tables. These enums are used for interfacing with API functions

vv.api.transparency_mode = {
  none = 1,
  clear = 2,
  all = 3,
}

vv.api.key_event_type = {
  press = 1,
  ['repeat'] = 2,
  release = 3,
}

vv.api.key_modifiers = {
  shift = 1,
  alt = 2,
  ctrl = 4,
  super = 8,
  hyper = 16,
  meta = 32,
  caps_lock = 64,
  num_lock = 128,
}

