--- DO NOT EDIT THIS BY HAND
--- This file was auto generated by api_gen.lua
--- It sets all options to their default values.

vv.options.focus_follows_mouse = true
vv.options.key_repeat_timeout = 500
vv.options.display_damage = false
vv.options.theme = {
  background = "#1e1e2e",
  black = "#45475a",
  blue = "#89b4fa",
  bright_black = "#585b70",
  bright_blue = "#89b4fa",
  bright_cyan = "#94e2d5",
  bright_green = "#a6e3a1",
  bright_magenta = "#f5c2e7",
  bright_red = "#f38ba8",
  bright_white = "#a6adc8",
  bright_yellow = "#f9e2af",
  cursor_background = "#f5e0dc",
  cursor_foreground = "#1e1e2e",
  cyan = "#94e2d5",
  foreground = "#cdd6f4",
  green = "#a6e3a1",
  magenta = "#f5c2e7",
  red = "#f38ba8",
  white = "#bac2de",
  yellow = "#f9e2af"
}

