local M = {}
local utils = require('utils')

--- @param spec spec
--- @return string _api.lua
function M.generate(spec)
  local builder = utils.builder()
  builder:push([=[
--[[
DO NOT EDIT THIS BY HAND
This file was auto generated by generate.lua
--]]

error("Cannot require meta file")

--- @meta
--- @class velvet.api
local api = {}]=])

  for _, enum in ipairs(spec.enums) do
    local lua_name = utils.get_luaname(enum.name)
    builder:push('\n---@alias <name> string <doc>', { name = lua_name, doc = enum.doc or "" })
    for _, v in ipairs(enum.values) do
      builder:push("---| '<name>' <doc>", { name = v.name, doc = v.doc or "" })
    end
    if enum.flags then
      builder:push('\n--- @class <name>s Flags for <name>', { name = lua_name })
      for _, value in ipairs(enum.values) do
        builder:push('--- @field <field>? boolean <doc>', { field = value.name, doc = value.doc or "" })
      end
    end
  end

  for _, type in ipairs(spec.types) do
    builder:push('\n--- @class <name>', { name = utils.get_luaname(type.name) })
    for _, fld in ipairs(type.fields) do
      local typename = utils.lua_type(fld.type) .. (fld.alias and ('|velvet.api.' .. fld.alias) or '')
      local t = utils.type_lookup[fld.type]
      if t.enumeration and t.enumeration.flags then
        typename = typename .. 's'
      end
      builder:push('--- @field <field> <type> <doc>',
        { field = fld.name .. (fld.optional and '?' or ''), type = typename, doc = fld.doc or "" })
    end
  end

  for _, fn in ipairs(spec.api) do
    builder:push('\n--- <doc>', { doc = utils.string_concatenate(fn.doc, "\n--- ") })
    for _, p in ipairs(fn.params or {}) do
      local t = utils.type_lookup[p.type]
      local optional = p.optional == true or t.optional == true or p.default_value ~= nil
      builder:push('--- @param <name> <type> <doc>',
        {
          name = p.name .. (optional and '?' or ''),
          doc = utils.string_concatenate(p.doc, "\n--- "),
          type = utils
              .lua_type(p.type)
        })
    end

    local params = {}
    for _, p in ipairs(fn.params or {}) do
      table.insert(params, p.name)
    end
    builder:push('--- @return <type> <ret> <doc>',
      {
        ret = fn.returns.name,
        type = utils.lua_type(fn.returns.type),
        doc = utils.string_concatenate(fn.returns.doc,
          "\n--- ")
      })

    builder:push("function api.<name>(<params>) end",
      { name = fn.name, params = table.concat(params, ", ") })
  end

  builder:push([[

--- @class velvet.api.event_handler
--- @field name string The name of the handler
--- @field id integer The id of the handler]])
  for _, evt in ipairs(spec.events) do
    local template = { field = evt.name:gsub('%.', '_'), args = evt.args, doc = evt.doc }
    builder:push('--- @field <field>? fun(event_args: velvet.api.<args>): nil <doc>', template)
  end

  return builder:tostring()
end

return M
