local M = {}
local utils = require('utils')

--- @param spec spec
--- @return string async_wait_functions.lua
function M.generate(spec)
  local builder = utils.builder()

  builder:push([==[
--[[
DO NOT EDIT THIS BY HAND
This file was generated by generate.lua
--]]

local M = {}

local function when_impl(reg, event)
  return reg.inner_when(event.data)
end

local function wait_impl(event, timeout, when)
  assert(type(when) == 'nil' or type(when) == 'function',
    string.format("Bad argument #2 (function expected, got %s)", type(when)))
  assert(type(timeout) == 'nil' or math.type(timeout) == 'integer',
    string.format("Bad argument #1 (integer expected, got %s)", type(timeout)))

  local registration = event
  if when then
    registration = { event = event, inner_when = when, when = when_impl }
  end

  local _, result = M.wait(registration, timeout)
  return result.data
end

--- @type table<string, string>
local known_events = {]==])

  for _, evt in ipairs(spec.events) do
    builder:push("  [ [[<name>]] ] = [[<doc>]],", { name = evt.name, doc = evt.doc })
  end

  builder:push([[
}

--- @alias velvet.async.event]])
  for _, evt in ipairs(spec.events) do
    builder:push("---| '<name>' <doc>", { name = evt.name, doc = evt.doc })
  end

  for _, evt in ipairs(spec.events) do
    builder:push([[

--- Wait for <name>
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.<return_type>> predicate function
--- @return velvet.api.<return_type> ret Result, or nil on timeout.
function M.wait_for_<event>(timeout, when)
  return wait_impl('<name>', timeout, when)
end]], { name = evt.name, return_type = evt.args, event = evt.name:gsub('%.', '_') })
  end

  builder:push("\nreturn { known_events, M }\n")

  return builder:tostring()
end

return M
