local M = {}
local utils = require('utils')
local inspect = require('velvet.inspect')

--- @param spec spec
--- @return string default_options.lua
function M.generate(spec)
  local builder = utils.builder()

  builder:push([[
--- DO NOT EDIT THIS BY HAND
--- This file was auto generated by generate.lua
--- It sets all options to their default values.
]])

  for _, fn in ipairs(spec.options) do
    local template = { name = fn.name, default_value = type(fn.default) == 'table' and inspect(fn.default) or fn.default }
    builder:push('vv.options.<name> = <default_value>', template)
  end

  builder:push("\n")
  return builder:tostring()
end

return M
