local M = {}
local utils = require('utils')

--- @param spec spec
--- @return string velvet_api.h
function M.generate(spec)
  local builder = utils.builder()
  builder:push([[
/***************************************************
************ DO NOT EDIT THIS BY HAND **************
*** This file was auto generated by generate.lua ****
***************************************************/

#ifndef VELVET_API_H
#define VELVET_API_H

#include "lua.h"
#include <stdbool.h>
#include "collections.h"

typedef lua_Integer lua_stackIndex;
typedef lua_Integer lua_stackRetCount;
struct velvet;]])

  --- C enums {{{3
  for _, enum in ipairs(spec.enums) do
    local cname = utils.get_cname(enum.name)
    if enum.doc then builder:push("/* <doc> */", { doc = enum.doc }) end
    builder:push('enum <packed><name> {', { packed = enum.packed and "__attribute__((packed)) " or "", name = cname })
    for _, v in ipairs(enum.values) do
      if v.doc then builder:push("  /* <doc> */", { doc = v.doc }) end
      local field_name = ("%s_%s"):format(cname, v.name):upper()
      builder:push('  <name> = <value>,', { name = field_name, value = v.value })
    end
    builder:push('};\n')
  end

  -- Create structs for composite types.
  -- These structs will automatically be marshaled to and from lua
  for _, type in ipairs(spec.types) do
    if utils.is_manual(type.name) then
      goto continue
    end
    if type.doc then builder:push("/* <doc> */", { doc = type.doc }) end
    local cname = utils.get_cname(type.name)
    builder:push('struct <name> {', { name = cname })
    for _, fld in ipairs(type.fields) do
      if fld.doc then builder:push("  /* <doc> */", { doc = fld.doc }) end
      if fld.optional then
        builder:push([[
  struct {
    <field_name> value;
    bool set;
  } <name>;]], { field_name = utils.c_type(fld.type), name = fld.name })
      else
        builder:push('  <type> <name>;', { type = utils.c_type(fld.type), name = fld.name })
      end
    end
    builder:push('};\n')
    ::continue::
  end

  for _, evt in ipairs(spec.events) do
    local event_name = evt.name:gsub("%.", "_")
    local event_arg_name = utils.get_cname(evt.args)
    builder:push('/* <doc> */', { doc = evt.doc })
    builder:push('void velvet_api_raise_<event>(struct velvet *v, __attribute__((unused)) struct <arg_type> args);',
      { event = event_name, arg_type = event_arg_name })
  end

  builder:push("\n#endif /* VELVET_API_H */\n")
  return builder:tostring()
end

return M
