local M = {}
local utils = require('utils')

--- @param spec spec
--- @return string velvet_lua_bindings_c
function M.generate(spec)
  local builder = utils.builder()
  builder:push([[
/***************************************************
************ DO NOT EDIT THIS BY HAND **************
*** This file was auto generated by generate.lua ****
***************************************************/

#include "lua.h"
#include "lauxlib.h"
#include "velvet_api.h"
#include "velvet_lua.h"
#include "velvet.h"
#include "velvet_enum_converters.c"
]])

  -- C API function marshalling {{{3

  for _, fn in ipairs(spec.api) do
    local manual_return = utils.is_manual(fn.returns.type)
    local has_manual_param = false

    for _, p in ipairs(fn.params or {}) do
      if utils.is_manual(p.type) then
        has_manual_param = true
        break
      end
    end

    builder.indent = 0
    builder:push('static int l_vv_api_<name>(lua_State *L) {', { name = fn.name })
    builder.indent = 2
    builder:push([[
lua_Integer argtop = <argc>;
(void)argtop;
struct velvet *v = *(struct velvet **)lua_getextraspace(L);
if (v->reloading) {
  lua_pushstring(L, "vv.api cannot be used after calling reload.");
  lua_error(L);
}
v->current = L;
]], { argc = #fn.params })

    local args = {}
    for idx, p in ipairs(fn.params or {}) do
      table.insert(args, p.name)
      local t = utils.type_lookup[p.type]
      if utils.is_manual(p.type) then
        -- pass the stack index; the implementation reads it from L
        builder:push("lua_Integer <name> = <idx>;", { name = p.name, idx = idx })
      elseif t.composite then
        if not t.optional then
          builder:push('luaL_checktype(L, <idx>, LUA_TTABLE);', { idx = idx })
        end
        builder:push([[
<type> <name> = {0};
if (!lua_isnoneornil(L, <idx>)) {
  luaL_checktype(L, <idx>, LUA_TTABLE);
  lua_pushvalue(L, <idx>); /* push table to the top of the stack */
]], { type = utils.c_type(p.type), name = p.name, idx = idx })
        builder.indent = builder.indent + 2
        utils.check.field(builder, p.type, p.name, p.default_value)
        builder:push('lua_pop(L, 1); /* pop pushed table */')
        builder.indent = builder.indent - 2
        builder:push('}')
      elseif t and t.enumeration then
        local template = {
          slice = p.name .. '_str',
          name = p.name,
          check = utils.lua_check('string', idx),
          struct = utils.c_type(p.type),
          type = p.type,
        }
        if p.default_value == nil then
          builder:push([[
struct u8_slice <slice> = <check>;
<struct> <name> = <type>_slice_to_enum(<slice>);]], template)
        else
          template.idx = idx
          template.default_value = p.default_value
          builder:push([[
struct u8_slice <slice>;
if (lua_isstring(L, <idx>)) {
  <slice> = <check>;
} else {
  <slice> = u8_slice_from_cstr("<default_value>");
}
<struct> <name> = <type>_slice_to_enum(<slice>);]], template)
        end
      else
        local template = { type = utils.c_type(p.type), name = p.name, check = utils.lua_check(p.type, idx) }
        if p.optional then
          template.test = utils.lua_test(p.type, idx)
          builder:push([[struct optional_<type> <name> = {0};
if (<test>) {
  <name>.set = true;
  <name>.value = <check>;
}]], template)
        else
          builder:push("<type> <name> = <check>; /* poggies */", template)
        end
      end
    end

    local argsstring = #args > 0 and ", " .. table.concat(args, ", ") or ""
    if has_manual_param or manual_return then
      builder:push('return vv_api_<name>(v<args>);', { name = fn.name, args = argsstring })
    elseif fn.returns.type == 'void' then
      builder:push('vv_api_<name>(v<args>);', { name = fn.name, args = argsstring })
      builder:push('return 0;')
    else
      local template = { struct = utils.c_type(fn.returns.type), name = fn.name, args = argsstring }
      if fn.returns.optional then
        builder:push([[
struct optional_<struct> ret = vv_api_<name>(v<args>);
if (!ret.set) {
  return 0;
}]], template)
        utils.push.field(builder, fn.returns.type, "ret.value")
      else
        builder:push('<struct> ret = vv_api_<name>(v<args>);', template)
        utils.push.field(builder, fn.returns.type, "ret")
      end
      builder:push('return 1;')
    end
    builder.indent = 0
    builder:push('}\n')
  end

  -- Generate lua function table {{{3

  builder:push('static const struct luaL_Reg velvet_lua_function_table[] = {')

  for _, fn in ipairs(spec.options) do
    builder:push('  { "get_<name>", l_vv_api_get_<name> },', { name = fn.name })
    builder:push('  { "set_<name>", l_vv_api_set_<name> },', { name = fn.name })
  end

  for _, fn in ipairs(spec.api) do
    builder:push('  { "<name>", l_vv_api_<name> },', { name = fn.name })
  end


  builder:push('  {0} /* sentinel */\n};\n')
  return builder:tostring()
end

return M
