local M = {}
local utils = require('utils')

--- @param spec spec
--- @return string velvet_enum_converters_c
function M.generate(spec)
  local builder = utils.builder()
  builder:push([[
/***************************************************
************ DO NOT EDIT THIS BY HAND **************
*** This file was auto generated by generate.lua ****
***************************************************/
#include "velvet_api.h"]])

  for _, enum in ipairs(spec.enums) do
    local cname = utils.get_cname(enum.name)
    -- String to integer value {{{4
    builder:push('\n__attribute__((unused)) static int <enum>_slice_to_enum(struct u8_slice str) {',
      { enum = enum.name })
    for _, option in ipairs(enum.values) do
      local template = { option = option.name, len = #option.name, value = utils.enum_value_c_name(cname, option.name) }
      builder:push('  struct u8_slice <option>_str = {.content = (const uint8_t *)"<option>", .len = <len>};', template)
      builder:push('  if (u8_slice_equals(str, <option>_str))\n    return <value>;\n', template)
    end
    builder:push('  return ~0;\n}')

    -- Integer value to string {{{4
    builder:push('\n__attribute__((unused)) static struct u8_slice <name>_to_slice(<type> value) {',
      { name = enum.name, type = utils.c_type(enum.name) })
    builder:push('  switch (value) {')
    for _, option in ipairs(enum.values) do
      local enum_value = (cname .. '_' .. option.name):upper()
      builder:push(
        '  case <value>:\n    return (struct u8_slice){.content = (const uint8_t *)"<option>", .len = <len>};',
        { value = enum_value, option = option.name, len = #option.name })
    end
    builder:push('  default: assert(!"<name> value out of range");', { name = enum.name });
    builder:push('  };\n}')
  end

  return builder:tostring()
end

return M
