local M = {}
local utils = require('utils')

--- @param spec spec
--- @return string velvet_lua_event_emitters_c
function M.generate(spec)
  local builder = utils.builder()
  builder:push([[
/***************************************************
************ DO NOT EDIT THIS BY HAND **************
*** This file was auto generated by generate.lua ****
***************************************************/

#include "lua.h"
#include "velvet_api.h"
#include "velvet_lua.h"
#include "velvet.h"
#include "utils.h"
#include "velvet_enum_converters.c"
]])

  for _, evt in ipairs(spec.events) do
    local template = {
      event = evt.name,
      arg = utils.get_cname(evt.args),
      value = evt.name,
      len = #evt
          .name
    }
    builder:push('void velvet_api_raise_<event>(struct velvet *v, __attribute__((unused)) struct <arg> args) {',
      template)
    builder:push([=[
  lua_State *L = v->L;
  if (!L) return;
  lua_getglobal(L, "vv");
  lua_getfield(L, -1, "events");
  lua_getfield(L, -1, "emit");
  lua_pushlstring(L, "<value>", <len>); /* event name */
  ]=], template)
    builder.indent = 2
    utils.push.field(builder, evt.args, "args")
    builder.indent = 0
    builder:push([[
  /* vv.events.emit(args) */
  if (lua_pcall(L, 2, 0, 0) != LUA_OK) {
    const char *err = lua_tostring(L, -1);
    velvet_log("lua emit: %s", err);
    lua_pop(L, 1);
  }
  lua_pop(L, 2);
}]])
  end
  builder:push('')

  return builder:tostring()
end

return M
