--[[
DO NOT EDIT THIS BY HAND
This file was auto generated by api_gen.lua
--]]

local M = {}

--- @type table<string, string|boolean>
local known_events = {
  [ [[on_key]] ] = [[Raised when a key is pressed.]],
  [ [[window.created]] ] = [[Raised after a new window is created.]],
  [ [[window.closed]] ] = [[Raised after a window is closed.]],
  [ [[window.output]] ] = [[Raised when a window produces output.]],
  [ [[window.bell]] ] = [[Raised when a window sends BEL.]],
  [ [[window.moved]] ] = [[Raised after a window is moved.]],
  [ [[window.resized]] ] = [[Raised after a window is resized.]],
  [ [[window.on_key]] ] = [[Raised when a key is sent to a lua window.]],
  [ [[window.focus_changed]] ] = [[Raised after focus changes.]],
  [ [[screen.resized]] ] = [[Raised after the screen is resized.]],
  [ [[mouse.move]] ] = [[Raised when the mouse moves.]],
  [ [[mouse.click]] ] = [[Raised when the mouse is clicked.]],
  [ [[mouse.scroll]] ] = [[Raised when the mouse scrolls.]],
  [ [[process.output]] ] = [[Raised when a process produces output.]],
  [ [[process.exited]] ] = [[Raised when a process exits.]],
  [ [[system_message]] ] = [[Raised when the system logs an error message]],
  [ [[pre_render]] ] = [[Raised right before content is rendered. This is useful for applying updates just-in-time.]],
  [ [[pre_reload]] ] = [[Raised before reloading. This event can be used to store state.]],
}

--- @alias velvet.async.event
---| 'on_key' Raised when a key is pressed.
---| 'window.created' Raised after a new window is created.
---| 'window.closed' Raised after a window is closed.
---| 'window.output' Raised when a window produces output.
---| 'window.bell' Raised when a window sends BEL.
---| 'window.moved' Raised after a window is moved.
---| 'window.resized' Raised after a window is resized.
---| 'window.on_key' Raised when a key is sent to a lua window.
---| 'window.focus_changed' Raised after focus changes.
---| 'screen.resized' Raised after the screen is resized.
---| 'mouse.move' Raised when the mouse moves.
---| 'mouse.click' Raised when the mouse is clicked.
---| 'mouse.scroll' Raised when the mouse scrolls.
---| 'process.output' Raised when a process produces output.
---| 'process.exited' Raised when a process exits.
---| 'system_message' Raised when the system logs an error message
---| 'pre_render' Raised right before content is rendered. This is useful for applying updates just-in-time.
---| 'pre_reload' Raised before reloading. This event can be used to store state.

--- Wait for on_key
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.on_key.event_args): boolean predicate function
--- @return velvet.api.on_key.event_args ret Result, or nil on timeout.
function M.wait_for_on_key(timeout, when)
  local event = 'on_key'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for window.created
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.window.created.event_args): boolean predicate function
--- @return velvet.api.window.created.event_args ret Result, or nil on timeout.
function M.wait_for_window_created(timeout, when)
  local event = 'window.created'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for window.closed
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.window.closed.event_args): boolean predicate function
--- @return velvet.api.window.closed.event_args ret Result, or nil on timeout.
function M.wait_for_window_closed(timeout, when)
  local event = 'window.closed'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for window.output
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.window.output.event_args): boolean predicate function
--- @return velvet.api.window.output.event_args ret Result, or nil on timeout.
function M.wait_for_window_output(timeout, when)
  local event = 'window.output'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for window.bell
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.window.bell.event_args): boolean predicate function
--- @return velvet.api.window.bell.event_args ret Result, or nil on timeout.
function M.wait_for_window_bell(timeout, when)
  local event = 'window.bell'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for window.moved
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.window.moved.event_args): boolean predicate function
--- @return velvet.api.window.moved.event_args ret Result, or nil on timeout.
function M.wait_for_window_moved(timeout, when)
  local event = 'window.moved'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for window.resized
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.window.resized.event_args): boolean predicate function
--- @return velvet.api.window.resized.event_args ret Result, or nil on timeout.
function M.wait_for_window_resized(timeout, when)
  local event = 'window.resized'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for window.on_key
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.window.on_key.event_args): boolean predicate function
--- @return velvet.api.window.on_key.event_args ret Result, or nil on timeout.
function M.wait_for_window_on_key(timeout, when)
  local event = 'window.on_key'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for window.focus_changed
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.window.focus_changed.event_args): boolean predicate function
--- @return velvet.api.window.focus_changed.event_args ret Result, or nil on timeout.
function M.wait_for_window_focus_changed(timeout, when)
  local event = 'window.focus_changed'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for screen.resized
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.screen.resized.event_args): boolean predicate function
--- @return velvet.api.screen.resized.event_args ret Result, or nil on timeout.
function M.wait_for_screen_resized(timeout, when)
  local event = 'screen.resized'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for mouse.move
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.mouse.move.event_args): boolean predicate function
--- @return velvet.api.mouse.move.event_args ret Result, or nil on timeout.
function M.wait_for_mouse_move(timeout, when)
  local event = 'mouse.move'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for mouse.click
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.mouse.click.event_args): boolean predicate function
--- @return velvet.api.mouse.click.event_args ret Result, or nil on timeout.
function M.wait_for_mouse_click(timeout, when)
  local event = 'mouse.click'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for mouse.scroll
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.mouse.scroll.event_args): boolean predicate function
--- @return velvet.api.mouse.scroll.event_args ret Result, or nil on timeout.
function M.wait_for_mouse_scroll(timeout, when)
  local event = 'mouse.scroll'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for process.output
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.process.output.event_args): boolean predicate function
--- @return velvet.api.process.output.event_args ret Result, or nil on timeout.
function M.wait_for_process_output(timeout, when)
  local event = 'process.output'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for process.exited
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.process.exit.event_args): boolean predicate function
--- @return velvet.api.process.exit.event_args ret Result, or nil on timeout.
function M.wait_for_process_exited(timeout, when)
  local event = 'process.exited'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for system_message
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.system_message.event_args): boolean predicate function
--- @return velvet.api.system_message.event_args ret Result, or nil on timeout.
function M.wait_for_system_message(timeout, when)
  local event = 'system_message'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for pre_render
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.pre_render.event_args): boolean predicate function
--- @return velvet.api.pre_render.event_args ret Result, or nil on timeout.
function M.wait_for_pre_render(timeout, when)
  local event = 'pre_render'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

--- Wait for pre_reload
--- @param timeout? integer Optional timeout.
--- @param when? fun(event: string, data: velvet.api.pre_reload.event_args): boolean predicate function
--- @return velvet.api.pre_reload.event_args ret Result, or nil on timeout.
function M.wait_for_pre_reload(timeout, when)
  local event = 'pre_reload'
  local registration = when and { event = event, when = when } or event
  local _, result = M.wait(registration, timeout)
  return result.data
end

return { known_events, M }
