--[[
DO NOT EDIT THIS BY HAND
This file was generated by generate.lua
--]]

local M = {}

local function when_impl(reg, event)
  return reg.inner_when(event.data)
end

local function wait_impl(event, timeout, when)
  assert(type(when) == 'nil' or type(when) == 'function',
    string.format("Bad argument #2 (function expected, got %s)", type(when)))
  assert(type(timeout) == 'nil' or math.type(timeout) == 'integer',
    string.format("Bad argument #1 (integer expected, got %s)", type(timeout)))

  local registration = event
  if when then
    registration = { event = event, inner_when = when, when = when_impl }
  end

  local _, result = M.wait(registration, timeout)
  return result.data
end

--- @type table<string, string>
local known_events = {
  [ [[on_key]] ] = [[Raised when a key is pressed.]],
  [ [[window.created]] ] = [[Raised after a new window is created.]],
  [ [[window.closed]] ] = [[Raised after a window is closed.]],
  [ [[window.output]] ] = [[Raised when a window produces output.]],
  [ [[window.bell]] ] = [[Raised when a window sends BEL.]],
  [ [[window.moved]] ] = [[Raised after a window is moved.]],
  [ [[window.resized]] ] = [[Raised after a window is resized.]],
  [ [[window.on_key]] ] = [[Raised when a key is sent to a lua window.]],
  [ [[window.focus_changed]] ] = [[Raised after focus changes.]],
  [ [[screen.resized]] ] = [[Raised after the screen is resized.]],
  [ [[mouse.move]] ] = [[Raised when the mouse moves.]],
  [ [[mouse.click]] ] = [[Raised when the mouse is clicked.]],
  [ [[mouse.scroll]] ] = [[Raised when the mouse scrolls.]],
  [ [[system_message]] ] = [[Raised when the system logs an error message]],
  [ [[pre_render]] ] = [[Raised right before content is rendered. This is useful for applying updates just-in-time.]],
  [ [[pre_reload]] ] = [[Raised before reloading. This event can be used to store state.]],
}

--- @alias velvet.async.event
---| 'on_key' Raised when a key is pressed.
---| 'window.created' Raised after a new window is created.
---| 'window.closed' Raised after a window is closed.
---| 'window.output' Raised when a window produces output.
---| 'window.bell' Raised when a window sends BEL.
---| 'window.moved' Raised after a window is moved.
---| 'window.resized' Raised after a window is resized.
---| 'window.on_key' Raised when a key is sent to a lua window.
---| 'window.focus_changed' Raised after focus changes.
---| 'screen.resized' Raised after the screen is resized.
---| 'mouse.move' Raised when the mouse moves.
---| 'mouse.click' Raised when the mouse is clicked.
---| 'mouse.scroll' Raised when the mouse scrolls.
---| 'system_message' Raised when the system logs an error message
---| 'pre_render' Raised right before content is rendered. This is useful for applying updates just-in-time.
---| 'pre_reload' Raised before reloading. This event can be used to store state.

--- Wait for on_key
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.on_key.event_args> predicate function
--- @return velvet.api.on_key.event_args ret Result, or nil on timeout.
function M.wait_for_on_key(timeout, when)
  return wait_impl('on_key', timeout, when)
end

--- Wait for window.created
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.window.created.event_args> predicate function
--- @return velvet.api.window.created.event_args ret Result, or nil on timeout.
function M.wait_for_window_created(timeout, when)
  return wait_impl('window.created', timeout, when)
end

--- Wait for window.closed
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.window.closed.event_args> predicate function
--- @return velvet.api.window.closed.event_args ret Result, or nil on timeout.
function M.wait_for_window_closed(timeout, when)
  return wait_impl('window.closed', timeout, when)
end

--- Wait for window.output
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.window.output.event_args> predicate function
--- @return velvet.api.window.output.event_args ret Result, or nil on timeout.
function M.wait_for_window_output(timeout, when)
  return wait_impl('window.output', timeout, when)
end

--- Wait for window.bell
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.window.bell.event_args> predicate function
--- @return velvet.api.window.bell.event_args ret Result, or nil on timeout.
function M.wait_for_window_bell(timeout, when)
  return wait_impl('window.bell', timeout, when)
end

--- Wait for window.moved
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.window.moved.event_args> predicate function
--- @return velvet.api.window.moved.event_args ret Result, or nil on timeout.
function M.wait_for_window_moved(timeout, when)
  return wait_impl('window.moved', timeout, when)
end

--- Wait for window.resized
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.window.resized.event_args> predicate function
--- @return velvet.api.window.resized.event_args ret Result, or nil on timeout.
function M.wait_for_window_resized(timeout, when)
  return wait_impl('window.resized', timeout, when)
end

--- Wait for window.on_key
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.window.on_key.event_args> predicate function
--- @return velvet.api.window.on_key.event_args ret Result, or nil on timeout.
function M.wait_for_window_on_key(timeout, when)
  return wait_impl('window.on_key', timeout, when)
end

--- Wait for window.focus_changed
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.window.focus_changed.event_args> predicate function
--- @return velvet.api.window.focus_changed.event_args ret Result, or nil on timeout.
function M.wait_for_window_focus_changed(timeout, when)
  return wait_impl('window.focus_changed', timeout, when)
end

--- Wait for screen.resized
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.screen.resized.event_args> predicate function
--- @return velvet.api.screen.resized.event_args ret Result, or nil on timeout.
function M.wait_for_screen_resized(timeout, when)
  return wait_impl('screen.resized', timeout, when)
end

--- Wait for mouse.move
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.mouse.move.event_args> predicate function
--- @return velvet.api.mouse.move.event_args ret Result, or nil on timeout.
function M.wait_for_mouse_move(timeout, when)
  return wait_impl('mouse.move', timeout, when)
end

--- Wait for mouse.click
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.mouse.click.event_args> predicate function
--- @return velvet.api.mouse.click.event_args ret Result, or nil on timeout.
function M.wait_for_mouse_click(timeout, when)
  return wait_impl('mouse.click', timeout, when)
end

--- Wait for mouse.scroll
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.mouse.scroll.event_args> predicate function
--- @return velvet.api.mouse.scroll.event_args ret Result, or nil on timeout.
function M.wait_for_mouse_scroll(timeout, when)
  return wait_impl('mouse.scroll', timeout, when)
end

--- Wait for system_message
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.system_message.event_args> predicate function
--- @return velvet.api.system_message.event_args ret Result, or nil on timeout.
function M.wait_for_system_message(timeout, when)
  return wait_impl('system_message', timeout, when)
end

--- Wait for pre_render
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.pre_render.event_args> predicate function
--- @return velvet.api.pre_render.event_args ret Result, or nil on timeout.
function M.wait_for_pre_render(timeout, when)
  return wait_impl('pre_render', timeout, when)
end

--- Wait for pre_reload
--- @async always yields
--- @param timeout? integer Optional timeout.
--- @param when? velvet.async.single_when<velvet.api.pre_reload.event_args> predicate function
--- @return velvet.api.pre_reload.event_args ret Result, or nil on timeout.
function M.wait_for_pre_reload(timeout, when)
  return wait_impl('pre_reload', timeout, when)
end

return { known_events, M }
