#ifndef QUERIES_H
#define QUERIES_H

#include "collections.h"

enum emulator_query_type {
  REQUEST_PRIMARY_DEVICE_ATTRIBUTES,
  REQUEST_SECONDARY_DEVICE_ATTRIBUTES, /* CSI > c */
  REQUEST_TERTIARY_DEVICE_ATTRIBUTES,  /* ?? */
  REQUEST_STATUS_OK = 5,               /* CSI 5n */
  REQUEST_CURSOR_POSITION = 6,         /* CSI 6n */
  REQUEST_DEFAULT_FG,                  /* OSC 10 / OSC 11 */
  REQUEST_DEFAULT_BG,                  /* OSC 11 */
  REQUEST_DEFAULT_CURSOR_COLOR,        /* OSC 12 */
  REQUEST_WINDOW_TITLE,                /* CSI 22;2;t */
  REQUEST_WINDOW_ICON,                 /* CSI 22;1;t */
  REQUEST_BRACKETED_PASTE_STATUS,      /* CSI ? 2026 $ p */
  REQUEST_FOCUS_REPORTING_STATUS,      /* CSI ? 2027 $ p */
  REQUEST_EXTENDED_FEATURES,           /* CSI ? 2031 $ p */
  REQUEST_TRUECOLOR_STATUS,            /* CSI ? 2048 $ p */
  REQUEST_WINDOW_SIZE,                 /* CSI 18t */
};

static char *emulator_query_type_names[] = {
    [REQUEST_PRIMARY_DEVICE_ATTRIBUTES] = "REQUEST_PRIMARY_DEVICE_ATTRIBUTES",
    [REQUEST_SECONDARY_DEVICE_ATTRIBUTES] =
        "REQUEST_SECONDARY_DEVICE_ATTRIBUTES",
    [REQUEST_TERTIARY_DEVICE_ATTRIBUTES] = "REQUEST_TERTIARY_DEVICE_ATTRIBUTES",
    [REQUEST_STATUS_OK] = "REQUEST_STATUS_OK",
    [REQUEST_CURSOR_POSITION] = "REQUEST_CURSOR_POSITION",
    [REQUEST_DEFAULT_FG] = "REQUEST_DEFAULT_FG",
    [REQUEST_DEFAULT_BG] = "REQUEST_DEFAULT_BG",
    [REQUEST_DEFAULT_CURSOR_COLOR] = "REQUEST_DEFAULT_CURSOR_COLOR",
    [REQUEST_WINDOW_TITLE] = "REQUEST_WINDOW_TITLE",
    [REQUEST_WINDOW_ICON] = "REQUEST_WINDOW_ICON",
    [REQUEST_BRACKETED_PASTE_STATUS] = "REQUEST_BRACKETED_PASTE_STATUS",
    [REQUEST_FOCUS_REPORTING_STATUS] = "REQUEST_FOCUS_REPORTING_STATUS",
    [REQUEST_EXTENDED_FEATURES] = "REQUEST_EXTENDED_FEATURES",
    [REQUEST_TRUECOLOR_STATUS] = "REQUEST_TRUECOLOR_STATUS",
    [REQUEST_WINDOW_SIZE] = "REQUEST_WINDOW_SIZE",
};

struct emulator_query {
  enum emulator_query_type type;
  uint8_t st[2];
};

struct emulator_query_response {
  enum emulator_query_type query;
  int client_pty;
};

/* vec<struct request> */
typedef struct vec request_buffer;

#endif /*  QUERIES_H */
